# Манифест - Заголовок
apiVersion: apps/v1
kind: Deployment
# Манифест - Объект deployment
metadata:
  # Имя сервиса
  name: aspnetmicroservicetemplate
spec:
  # Количество реплик сервиса 
  replicas: 1
  selector:
    matchLabels:
      pod: aspnetmicroservicetemplate # Селектор для поиска подов
  template:
    # Манифест - Объект pod (PodSpec)
    metadata:
      labels:
        pod: aspnetmicroservicetemplate # Метаданные для поиска подов
    spec:
      containers:
        # Имя контейнера
      - name: aspnetmicroservicetemplate-container
        # Адрес образа на Docker Hub
        image: docker.io/vegiwoo/aspnetmicroservicetemplate:1.0.2
        ports:
        - containerPort: 8081
        # Readiness and liveness probes
        readinessProbe:
          initialDelaySeconds: 10 # Задержка перед проверкой
          periodSeconds: 30       # Период проверки
          # Выполняется этот http-запрос
          httpGet:
            path: /healthz
            port: 8081
            scheme: HTTP
          timeoutSeconds: 2       # Таймаут ответа на запрос
          failureThreshold: 1     # Количество допустимых неудачных попыток
          successThreshold: 1     # Количество необходимых успешных попыток
        livenessProbe:
          initialDelaySeconds: 30 
          periodSeconds: 30       
          httpGet:
            path: /readyz
            port: 8081
            scheme: HTTP
          timeoutSeconds: 5       
          failureThreshold: 10
          successThreshold: 1
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"