# Манифест - Заголовок
apiVersion: apps/v1
kind: Deployment
# Манифест - Объект deployment
metadata:
  # Имя сервиса
  name: aspnetmicroservicetemplate
spec:
  # Количество реплик сервиса 
  replicas: 1
  selector:
    matchLabels:
      pod: aspnetmicroservicetemplate # Селектор для поиска подов
  template:
    # Манифест - Объект pod (PodSpec)
    metadata:
      labels:
        pod: aspnetmicroservicetemplate # Метаданные для поиска подов
    spec:
      containers:
        # Имя контейнера
      - name: aspnetmicroservicetemplate-container
        # Адрес образа на Docker Hub
        image: docker.io/vegiwoo/aspnetmicroservicetemplate:1.0.1
        ports:
        - containerPort: 8081
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"

# ---
# apiVersion: v1
# kind: ServiceAccount
# metadata:
#   name: aspnetmicroservicetemplate-sa

# # Implemented separately for each individual service !

# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: aspnetmicroservicetemplate
#   labels:
#     app: aspnetmicroservicetemplate
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: aspnetmicroservicetemplate
#   template:
#     metadata:
#       labels:
#         app: aspnetmicroservicetemplate
#     spec:
#       containers:
#       - name: aspnetmicroservicetemplate
#         image: vegiwoo/aspnetmicroservicetemplate:0.0.12
#         ports:
#         - containerPort: 8081
#         env:
#         - name: ASPNETCORE_ENVIRONMENT
#           value: "Production"

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: aspnetmicroservicetemplate-nodeport
# spec:
#   type: NodePort
#   ports:
#   - port: 8081
#     targetPort: 8081
#     nodePort: 30001
#   selector:
#     app: aspnetmicroservicetemplate

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: aspnetmicroservicetemplate-clusterip
# spec:
#   type: ClusterIP
#   ports:
#   - port: 8081
#     targetPort: 8081
#   selector:
#     app: aspnetmicroservicetemplate
    
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: aspnetmicroservicetemplate-loadbalancer
# spec:
#   type: LoadBalancer
#   ports:
#   - port: 8081
#     targetPort: 8081
#   selector:
#     app: aspnetmicroservicetemplate