# Манифест - Заголовок
apiVersion: apps/v1
kind: Deployment
# Манифест - Объект deployment
metadata:
  # Имя сервиса
  name: service01
  namespace: default
spec:
  # Количество реплик сервиса 
  replicas: 1
  selector:
    matchLabels:
      app: service01 # Селектор для поиска подов
  # Указание стратегии обновления
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1 # Количество подов, которые могут быть недоступны во время обновления
      maxSurge: 2       # Количество подов, которые могут быть созданы во время обновления
  template:
    # Манифест - Объект pod (PodSpec)
    metadata:
      labels:
        app: service01 # Метаданные для поиска подов
    spec:
      priorityClassName: hight-priority # Указание класса приоритета
      containers:
        # Имя контейнера
      - name: service01-container
        # Адрес образа на Docker Hub
        image: docker.io/vegiwoo/aspnetmicroservicetemplate:1.0.35
        resources:
          # Ресурсы, которые будут выделены контейнеру
          requests:
            memory: "128Mi" # Минимально необходимая память в мебибайтах 
            cpu: "128m"     # Минимально необходимый CPU в миллиярдных долях (250m = 25% ядра)
          # Лимиты, которые могут быть выделены контейнеру
          limits:
            memory: "128Mi"   # Максимально допустимая память в мебибайтах 
            cpu: "128m"       # Максимально допустимый CPU
        ports:  
        - containerPort: 8081
        # Readiness and liveness probe
        readinessProbe:
          initialDelaySeconds: 10 # Задержка перед проверкой
          periodSeconds: 30       # Период проверки
          # Выполняется этот http-запрос
          httpGet:
            path: /api/ready
            port: 8081
            scheme: HTTP
          timeoutSeconds: 2       # Таймаут ответа на запрос
          failureThreshold: 1     # Количество допустимых неудачных попыток
          successThreshold: 1     # Количество необходимых успешных попыток
        livenessProbe:
          initialDelaySeconds: 30 
          periodSeconds: 30       
          httpGet:
            path: /api/health
            port: 8081
            scheme: HTTP
          timeoutSeconds: 5       
          failureThreshold: 3
          successThreshold: 1
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        # Test! 
        # - name: AVATAR_ENDPOINT
        #   value: https://robohash-cip:80 # Ссылка на сервис RoboHash
        # - name: NASDAQ_ENDPOINT
        #   value: http://nasdaq-cip # Ссылка на сервис Nasdaq Data Link