# Тестовый сервис - Спецификация
apiVersion: apps/v1
kind: Deployment
metadata:
  name: robohash
  namespace: ingress-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: robohash
  template:
    metadata:
      labels:  
        app: robohash
    spec:
      containers:
      - name: robohash-container
        image: wdenniss/robohash:3
---
# Тестовый сервис 2 - ClusterIP
apiVersion: v1
kind: Service
metadata:
  name: robohash-cip
  namespace: ingress-example
spec:
  selector:
    app: robohash
  ports:
  - protocol: TCP
    port: 8082
    targetPort: 8082
  type: ClusterIP