# Тестовый сервис 2 - Спецификация
apiVersion: apps/v1
kind: Deployment
metadata:
  name: robohash
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: robohash
  template:
    metadata:
      labels:  
        app: robohash
    spec:
      containers:
      - name: robohash-container
        image: wdenniss/robohash:3
        ports:  
        - containerPort: 8082
# ---
# # Тестовый сервис 2 - NodePort
# apiVersion: v1
# kind: Service
# metadata:
#   name: robohash-np
#   namespace: default
# spec:
#   selector:
#     app: robohash
#   ports:
#   - port: 8082
#     targetPort: 8082
#     protocol: TCP
#   type: NodePort
---
# Тестовый сервис 2 - ClusterIP
# - сервис достпен только внутри кластера
# ClusterIP для сервиса
# - сервис доступен только внутри кластера
apiVersion: v1
kind: Service
metadata:
  name: robohash-ip
  namespace: default
spec:
  selector:
    app: robohash
  ports:
  - protocol: TCP
    port: 8082
    targetPort: 8082
  type: ClusterIP