# Horizontal Pod Autoscaler (HPA)
# Автоматическое масштабирование подов
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: testservice01-hpa
  namespace: ingress-example
spec:
  minReplicas: 1
  maxReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: testservice01
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 20 # Целевое значение использования CPU в процентах